### ISSUE TITLE
Cursor moves out of the view when moving around with up/down key

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/text#1216]
**Describe the bug**
When opening a markdown file which is longer than the viewport and requires scrolling, the cursor may move outside the view before the view itself starts scrolling.

**To Reproduce**
1. Create a new markdown file
2. Add content so the while file is longer than the visible area in the browser
3. Scroll the file up, so the first line is at the top
4. Position the cusor in the first line
5. Start moving downwards with the cursor by pressing the cursor down key on the keyboard until the cursor reaches the lower end of the viewport but is still visible
6. Go down one line further

**Expected behavior**
The view scrolls as soon as the cursor is position to a line which is partially or completely outside the viewport.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/6613614/101094957-7d2b1a80-35bd-11eb-81ad-54b10191213b.png)

**Client details:**
 - OS: Windows 10 Pro
 - Browser: Firefox 83.0 / Vivaldi 3.4.2066.106
 - Device: Desktop

**Operating system:** Linux 4.15.0-126-generic #129-Ubuntu SMP Mon Nov 23 18:53:38 UTC 2020 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.1.47

**PHP version:** 

7.4.13
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, imap, intl, json, ldap, exif, memcache, mysqli, pdo_mysql, pdo_sqlite, apc, posix, pspell, readline, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 20.0.2 - 20.0.2.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.3
 - admin_audit: 1.10.0
 - apporder: 0.11.0
 - bruteforcesettings: 2.0.1
 - calendar: 2.1.2
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.4.2
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.1
 - deck: 1.2.2
 - drawio: 0.9.8
 - extract: 1.2.5
 - federatedfilesharing: 1.10.1
 - federation: 1.10.1
 - files: 1.15.0
 - files_downloadactivity: 1.9.0
 - files_mindmap: 0.0.23
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.0
 - files_texteditor: 2.14.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - forms: 2.0.4
 - gpxpod: 4.2.4
 - issuetemplate: 0.7.0
 - keeweb: 0.6.4
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - nextcloud_announcements: 1.9.0
 - notes: 4.0.1
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - onlyoffice: 6.1.0
 - password_policy: 1.10.1
 - phonetrack: 0.6.5
 - photos: 1.2.0
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - quota_warning: 1.9.1
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - socialsharing_email: 2.1.0
 - spreed: 10.0.3
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - tasks: 0.13.6
 - text: 3.1.0
 - theming: 1.11.0
 - theming_customcss: 1.7.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - encryption
 - files_external
 - files_markdown
 - recommendations
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.0x0c.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "skeletondirectory": "",
    "overwrite.cli.url": "https:\/\/nextcloud.0x0c.de",
    "dbtype": "mysql",
    "version": "20.0.2.2",
    "installed": true,
    "htaccess.RewriteBase": "\/",
    "maintenance": false,
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "knowledgebaseenabled": false,
    "theme": "",
    "simpleSignUpLink.shown": false,
    "loglevel": 2,
    "log_authfailip": true,
    "mysql.utf8mb4": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "sendmail",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "updater.release.channel": "stable",
    "trashbin_retention_obligation": "auto, 30",
    "app_install_overwrite": [
        "apporder",
        "deck",
        "keeweb"
    ],
    "has_rebuilt_cache": true,
    "onlyoffice": {
        "verify_peer_off": true
    }
}
```
</details>

**Are you using external storage, if yes which one:**

no

**Are you using encryption:** 

no

**Are you using an external user-backend, if yes which one:**

no

</details>

**Comment by arnowelzel** [comment]
Did anyone have a chance to look at this issue? It still exists and does not happen at https://tiptap.dev/, only in Nextcloud.

**Comment by svenb1234** [comment]
And it does not only affect reading but also writing. I.e. if one writes a text and get beyond the visible area at the bottom one writes without seeing the text. One has to scroll manually with the mouse or similar tool.

To me it seems that the space covered by the taskbar (in windows) is not deducted when calculating the available space.

**Comment by arnowelzel** [comment]
This issue is still present with Nextcloud Hub II (23.0.0). Any chance, that this can be fixed?

**Comment by juliushaertl** [comment]
Should be fixed with the recent changes with simplifying the editor structure and migrating to a newer upstream library version. I cannot reproduce this on 24 anymore.

**Comment by arnowelzel** [comment]
I can still reproduce this after updating from NC 23.0.4 to NC 24 - exactly the same behaviour.
