### ISSUE TITLE
Editing in code block does not work in firefox 

### ISSUE THREAD

**Issue by Aveyron-RetD** [nextcloud/text#5695]
**Describe the bug**
In text try to edit code blocks. Cursor is going everywhere, input is jumping from line to line

**To Reproduce**
Steps to reproduce the behavior: reproduced on firefox not on edge.
1. Insert some code 
2. Click on the code => Blue borders appears
3. ![image](https://github.com/nextcloud/text/assets/53221471/9c21431e-4b7d-4708-9af3-d96d557ec252)
4. Put the cursor to edit delete or add some stuff. Text is put in different sections of the code

**Expected behavior**
Cursor is put and follow normal behaviour.

**Screenshots**

**Server details:**
- Nextcloud version: 28.0.4
- PHP Version: [e.g. 8.2]
- Database: [e.g. MariaDB 10.6]

**Client details:**
 - OS: [e.g. Windows/macOS/Ubuntu]
 - Browser: [e.g. Firefox, Chrome] Firefox 125
 - Browser version: [e.g. 22]
 - Device: [e.g. iPhone6, desktop]

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by Aveyron-RetD** [comment]
Solved in 29.0.1

**Comment by XueSheng-GIT** [comment]
I'm also on NC 29.0.1 and for me the issue is only partly fixed. Those blue lines still appear (not sure what the meaning of this marking is) and adding or removing text by typing seems to work again.
But pasting text still does not work as expected (text is placed at different places) and the cursor jumps around.

@Aveyron-RetD Could you double check whether pasting text does work while the lines are marked blue?

@mejo- Should I create a new issue or would it be better to reopen this one?

**Comment by Aveyron-RetD** [comment]
@XueSheng-GIT you are right, and i can still re-trigger the original bug report /-(
sorry for the false report !!
re-opening as not fixed in 29.0.1

**Comment by mejo-** [comment]
Thanks for the reports everyone. So far I'm unable to reproduce this with latest Firefox (127.0) on Linux with Wayland. Could you give a few more details about your setup?

* Are you only able to reproduce this in Firefox, or also in Chrome/Chromium or other browsers?
* If it's only in Firefox, could you try to reproduce this in safe browsing mode with all add-ons disabled?
* Which operating systems do you use? Windows, Linux (X11 or Wayland?)?
* Did this bug appear after upgrading Nextcloud to a specific version? Is there other Nextcloud instances where the same problem doesn't exist?

**Comment by XueSheng-GIT** [comment]
@mejo- 
I tested firefox (127.0) on Ubuntu 24.04 (X11 and Wayland) and Windows 11.
I tested safe browsing mode.
But issue is always the same and this exists since text shows this blue border once you select text in code block.

Here's a short screencast. Sometimes pasted text also appears at some weird places outside of the code block (which is not shown in the screencast).
At the end of the screencast you'll see that if the blue border is not shown, pasting text works as expected.

[Bildschirmaufzeichnung vom 2024-06-16 07-09-59.webm](https://github.com/nextcloud/text/assets/4077683/94752e2e-209d-4426-9623-274509911e38)

**Comment by Aveyron-RetD** [comment]
I do not reproduce on edge as It is much more difficult to get those coloured borders. It is possible, but they disappear really quickly.

**Comment by mejo-** [comment]
To those who experienced this bug in the past: can you still reproduce it with latest Nextcloud 29.0.6 (or 30 release candidate)? I'm unable to reproduce the problems with editing or pasting in code block described above with Firefox 130 or Chromium 128 on Linux/Wayland. I *am* able to see the blue fences around text in code blocks with Firefox though.

The editing/pasting issues might have been a temporary bug in either Firefox or the Tiptap editor that got fixed in the meantime :thinking:

**Comment by mejo-** [comment]
The blue fences are the highlighting of `focus-visible` class in Firefox. There was a matching [bug in Firefox 110+111](https://bugzilla.mozilla.org/show_bug.cgi?id=1817634) but it got fixed in the 112 release.

Edit: The blue fence symptom disappears if I remove the [`tabindex="-1"` from the code element](https://github.com/nextcloud/text/blob/c7264fc3d7fb48e81eb04c367b26fbb34dfe1d05/src/nodes/CodeBlockView.vue#L72). It was introduced in 2c9e7a0fce22aab005b202a51b0bffcbfa47b0a8.

I tried tab navigation and focus trap with several other elements outside the editor and it seems they still worked after removing the `tabindex="-1"`. @juliushaertl do you still remember what exactly was fixed with the PR and could you check if it breaks again if you remove `tabindex="-1"`?

**Comment by XueSheng-GIT** [comment]
> To those who experienced this bug in the past: can you still reproduce it with latest Nextcloud 29.0.6 (or 30 release candidate)? I'm unable to reproduce the problems with editing or pasting in code block described above with Firefox 130 or Chromium 128 on Linux/Wayland. I _am_ able to see the blue fences around text in code blocks with Firefox though.
> 
> The editing/pasting issues might have been a temporary bug in either Firefox or the Tiptap editor that got fixed in the meantime 🤔

Still an issue on my end. NC29.0.6 with Firefox 130 (Ubuntu, Win11 and Android).
@mejo- did you have a look at my screencast? https://github.com/nextcloud/text/issues/5695#issuecomment-2171053533

Easiest way to force this issue is selecting part of a text within a code block an trying to paste it at some other place within the code block.

**Comment by mejo-** [comment]
@XueSheng-GIT thanks for the additional information. I was able to reproduce now. Removing `tabindex="-1"` from the code element in the HTML structure fixes the issue for me.
