### ISSUE TITLE
Tab key doesn't work, no way to indent.

### ISSUE THREAD

**Issue by jvalrog** [nextcloud/text#601]
**Describe the bug**
Can't indent code snippets or paragraphs in Text app.

**To Reproduce**
Hit tab.

**Expected behavior**
Add a tab character to the current line.

**Client details:**
 - OS: Linux (Docker)
 - Browser: Firefox 72 and Chrome 79
 - Device: Desktop

**Text app version:** 2.0.0

**Operating system:** Ubuntu 18.04

**Web server:** Apache (from Docker official image)

**Database:** Sqlite3

**PHP version:** 7.3.13

**Nextcloud version:** 18.0.0 stable

**Comment by daCaPo** [comment]
This probably would also improve compatibility with apps like iA Writer on iOS. Actually, NC Text and iA Writer treat lists with indentations differently:

- NC Text uses 2 space characters for list intendation
- iA can be configured to use spaces, but expects 4 spaces per intendation level

**Comment by juliushaertl** [comment]
> Can't indent code snippets or paragraphs in Text app.

Paragraph indentation is nothing that can be represented in markdown as trailing whitespace would just be removed. For code blocks we should fix this. :+1: 

> This probably would also improve compatibility with apps like iA Writer on iOS. Actually, NC Text and iA Writer treat lists with indentations differently:
> NC Text uses 2 space characters for list intendation
> iA can be configured to use spaces, but expects 4 spaces per intendation level

This is a different topic, please open a separate issue to discuss something like this. In general I would like to have some more information on how other markdown editors handle this, as two spaces are definitely fine according to the commonmark standard.

**Comment by Fmstrat** [comment]
This is a problem with bullet points, too.

**Comment by juliushaertl** [comment]
> This is a problem with bullet points, too. You have to backspace to make the bullets on one line, press enter again, then hit tab.

Please share some more detailed steps about that as I cannot see any issue with the tab indentation on lists:

![Peek 2020-06-15 12-09](https://user-images.githubusercontent.com/3404133/84645549-0a3fc180-af01-11ea-9521-bd47ea1e07fe.gif)

**Comment by Fmstrat** [comment]
@juliushaertl Ahh, good catch. I figured out the use case that was causing it. It was happening for me in every file because all of my files I was trying to change were formatted the same way.

Upload a file into Nextcloud of `test.md`:
```
This is a test with a blank line after it.

* Bullet 1
* Bullet 2
```

- Now open the file in Nextcloud Text, and place your cursor at the T in "This".
- Hit the ordered list button. You now have 3 bullets, however there is a "hidden" carriage return from the blank line that existed before
- Place your cursor next to the B in "Bullet 1"
- Press tab
- Focus goes up the browser's menu bar

To fix it, you have to backspace from "Bullet 1" up to the previous line and press enter. This makes since because there is actually an empty line there, but Text (or the editor, rather) isn't giving any indication the blank line is there.

**Comment by juliushaertl** [comment]
>  Maybe this is a Prosemirror thing?

Might be, could you check at https://tiptap.scrumpy.io/ if you can reproduce it there?

**Comment by Fmstrat** [comment]
Sure thing, and yes, to an extent. Since I can't start from raw MD I faked it by inserting a blank line and backspacing. You can see in the GIF. Process was:

- Type "test"
- Press enter twice
- Type "test"
- Ordered list button
- Go to blank line between "test"s
- Backspace
- Ordered list button (now that invisible return from the line is still there but you can't see it)
- Click on second line
- Tab (jumps out of editor instead of indenting)

![tabs](https://user-images.githubusercontent.com/971474/84659567-9cd26780-aee5-11ea-9eae-8c30fb2207e2.gif)

**Comment by PVince81** [comment]
is this something that needs to be implemented from scratch in whatever or is indenting supported by the underlying library and it's just a matter of calling the right function ? @juliushaertl

**Comment by mejo-** [comment]
I just tested this on latest Text in Nextcloud 24 and the bug has been fixed by the list item improvements by @max-nextcloud :tada:

**Comment by Isac99** [comment]
Looks like this bug is back in version 27.0.1 - just upgraded and the tab key no longer indents bullet points are unordered lists.

**Comment by mejo-** [comment]
@Isac99 I cannot reproduce this myself. But someone else reported this as well in #4389. Could you reply to my questions over [there](https://github.com/nextcloud/text/issues/4389#issuecomment-1649188328)?

**Comment by SmartLiving-Rocks** [comment]
> in version 27.0.1

In Version **27.0.2**, too (Docker nextcloud:27.0.2-apache)

**Comment by juliushaertl** [comment]
Should be fixed by #4735

**Comment by rhabacker** [comment]
This bug is also back in version 30.0.4 - the tab key no longer indents bullet points at unordered lists

**Comment by max-nextcloud** [comment]
> This bug is also back in version 30.0.4 - the tab key no longer indents bullet points at unordered lists

Just tested and could not reproduce. See video below. Could you provide step by step instructions how to reproduce?

https://github.com/user-attachments/assets/bfdb76bf-facb-44aa-9572-6487feb3c8d0

**Comment by rhabacker** [comment]
1. open the Readme.md file in my Nextcloud folder
2. select “unordered list” - a bullet point appears
3. enter text
4. press return - a new bullet point appears in the next line
5. press Tab - the cursor ('|') disappears
6. press the tab key again - a black rounded rectangle appears around the 'X' button in the top right-hand corner

It looks like the tab key changes the input focus to the next widget

I tested this with Firefox 128.6.0esr and Chrome 132.0.6834.83.

**Comment by tatrapikao** [comment]
> 1. open the Readme.md file in my Nextcloud folder
> 2. select “unordered list” - a bullet point appears
> 3. enter text
> 4. press return - a new bullet point appears in the next line
> 5. press Tab - the cursor ('|') disappears
> 6. press the tab key again - a black rounded rectangle appears around the 'X' button in the top right-hand corner
> 
> It looks like the tab key changes the input focus to the next widget
> 
> I tested this with Firefox 128.6.0esr and Chrome 132.0.6834.83.

Same Chromium 135.0.7049.52
