### ISSUE TITLE
When entering special symbols for Chinese, Japanese and Korean, the system will automatically wrap the line

### ISSUE THREAD

**Issue by ebfming** [nextcloud/text#7027]
**Describe the bug**
When you enter special characters in Chinese, Japanese and Korean languages, such as “：、?”, the system will automatically wrap
**To Reproduce**
Enter the above special characters in a blank line and they will appear. If there is text after the characters, this problem will not occur

**Expected behavior**
fix bug

**Server details:**
- Nextcloud version:31.0.2
- PHP Version: [e.g. 8.2]
- Database:mysql

**Client details:**
- OS: [e.g. Windows/macOS/Ubuntu] all
- Browser: Chrome
- Browser version: all

**Comment by joshtrichards** [comment]
May be a regression, since forum post suggests this did not occur with the stable29 (or at least 29.0.11 anyhow) shipped version of Text:

https://help.nextcloud.com/t/downgrading-nextcloud-text-app-from-version-31-0-2-to-version-29-11/222121

**Comment by ebfming** [comment]
> May be a regression, since forum post suggests this did not occur with the stable29 (or at least 29.0.11 anyhow) shipped version of Text:
> 
> https://help.nextcloud.com/t/downgrading-nextcloud-text-app-from-version-31-0-2-to-version-29-11/222121

That author is me. I chose to downgrade because this version has bugs.

**Comment by mejo-** [comment]
Hey @ebfming, are you still able to reproduce the problem with latest Nextcloud 31.0.7?

**Comment by ebfming** [comment]
> Hey [@ebfming](https://github.com/ebfming), are you still able to reproduce the problem with latest Nextcloud 31.0.7?

Even with the latest version, I tried, that's bug has also exist. I still used old version by text app.

It is worth mentioning that a new bug has been introduced. This is reflected in the IOS app. When opening the md file, as shown in the picture

<img width="1284" height="2778" alt="Image" src="https://github.com/user-attachments/assets/7d8d8585-4908-46f8-bd4a-461ef5e52906" />

**Comment by mejo-** [comment]
@ebfming thanks for your feedback. When I understand your screenshot correctly, the original bug that you reported in this issue has been fixed in the meantime, right?

Regarding the new bug, could you please open a new issue and describe there what exactly it is about? That would be really helpful 🙏

**Comment by ebfming** [comment]
> [@ebfming](https://github.com/ebfming) thanks for your feedback. When I understand your screenshot correctly, the original bug that you reported in this issue has been fixed in the meantime, right?
> 
> Regarding the new bug, could you please open a new issue and describe there what exactly it is about? That would be really helpful 🙏

The bugs were not fixed. I mean not only were the bugs not fixed, but new versions introduced new bugs.

**Comment by mejo-** [comment]
@ebfming thanks for the clarification.

Is this problem reproducible in the web version of Nextcloud Text, or do you only experience it when editing documents via the mobile apps?

**Comment by ebfming** [comment]
> [@ebfming](https://github.com/ebfming) thanks for the clarification.
> 
> Is this problem reproducible in the web version of Nextcloud Text, or do you only experience it when editing documents via the mobile apps?

That is, the text app that comes with 31.07 when it is installed.
If you use the text of 31.07 on the mobile terminal, then md files will not be able to open. It keeps loading.
https://help.nextcloud.com/t/regarding-some-question-with-text-in-nextcloud-app-on-ios-system/189822
I reported this problem a long time ago, and it was fixed after the upgrade, but since 31.x, this problem has reappeared. If I downgrade the text app to the built-in text app of the 29.11 version, everything is normal.

The mobile terminal effect shown in my last screenshot is the effect of the old version of text (29.11) I am currently using, not the actual effect of the text app that comes with 31.07. However, it is actually worse.
This is how I use it now with an older version of text (29.11)
https://help.nextcloud.com/t/downgrading-nextcloud-text-app-from-version-31-0-2-to-version-29-11/222121

**Comment by ebfming** [comment]
@mejo-   
hello mejo,
What’s the current status of this bug? Do you know in which version it will likely be fixed?
I’m very concerned about the progress, and I’m really looking forward to using the new version of the text app.
However, after updating to NC 31.0.8 yesterday, I still didn’t see the fix.

**Comment by DLW3D** [comment]
This issue still exists in Text 5.0.0 (Nextcloud 31.0.8).
It occurs on the Windows web client (both Chrome and Edge), but has not been observed on Chrome for Android.

Since this issue involves common Chinese punctuation marks—such as the full stop (。), colon (：), enumeration comma (、), and question mark (？)—it is preventing me from using Text and its downstream applications like Collectives.

Greatly appreciate any updates.

**Comment by ebfming** [comment]
> This issue still exists in Text 5.0.0 (Nextcloud 31.0.8). It occurs on the Windows web client (both Chrome and Edge), but has not been observed on Chrome for Android.
> 
> Since this issue involves common Chinese punctuation marks—such as the full stop (。), colon (：), enumeration comma (、), and question mark (？)—it is preventing me from using Text and its downstream applications like Collectives.
> 
> Greatly appreciate any updates.

yeah,in the MACOS safari and chrome browser the same yet

**Comment by mejo-** [comment]
I have hope that https://github.com/nextcloud/text/pull/7981 fixes the problem. If someone feels comfortable to build and test, that would be highly appreciated.

**Comment by ebfming** [comment]
> I have hope that [#7981](https://github.com/nextcloud/text/pull/7981) fixes the problem. If someone feels comfortable to build and test, that would be highly appreciated.

Thank you very much for finally resolving this issue! I see that the relevant Pull Request (#7981) has been merged, and I am very pleased that this bug has been fixed.

Thank you for inviting me to assist with testing. However, due to my environment constraints, I am currently unable to easily deploy and verify this specific branch/PR on a non-official build. I plan to test the fix immediately on my production environment once it is included in the next stable release or official version.

[Notification Request]

As I am unsure which specific version of the Nextcloud Text app this fix will be included in (e.g., Text App vX.Y.Z), I would greatly appreciate it if you could notify me in this Issue thread once the release version is confirmed. This will help me avoid having to manually check every Nextcloud release for this commit.

I will provide feedback immediately after confirming the version and completing the testing.

Thank you for your efforts and work!

**Comment by ebfming** [comment]
> I have hope that [#7981](https://github.com/nextcloud/text/pull/7981) fixes the problem. If someone feels comfortable to build and test, that would be highly appreciated.

I have reviewed your fix methodology (in PR #7981) and tried implementing a similar approach myself in the relevant file: `src/extensions/TextDirection.ts`.

After this attempt, the original issue regarding broken input for letters/text now seems to be resolved.

However, I found that **two related issues still persist.** Please refer to my attached screen recordings for details (one short clip demonstrating the main issue, and a longer clip showing the comprehensive effect):

### 1. Cursor Disappearance After Symbols

The issue where the cursor disappears still occurs after inputting certain special symbols.

* **Affected Symbols:** `?`, `!`, `:`, `，`, `。`, etc.
* **Effect:** The cursor vanishes, and the user must manually click the mouse inside the document to regain focus and continue typing.

### 2. Character Duplication Issue Reappears

The problem of **duplicated letters/characters** during Chinese input (linked to Issue #7789) *still reappears* under one specific condition:

* **Condition:** If a punctuation mark is used as the **first character** of a paragraph, subsequent Chinese input results in the letter duplication bug again.

---

My implementation may not be complete, and **I welcome any suggestions** regarding my approach or these remaining issues. I hope my screen recordings are helpful for your investigation.

Thank you!

**about screen vido**

https://github.com/user-attachments/assets/3f9ec7a5-fe6a-467c-a89d-ca681c4e5144

https://github.com/user-attachments/assets/63328aa9-e3f6-4351-b44c-ba149d20762c

**Comment by a15355447898a** [comment]
https://github.com/user-attachments/assets/b2b59b26-81ee-4f81-b537-6586086f4f1c

I can't type Chinese at all. Any progress on that?

**Comment by ebfming** [comment]
---

Hello @mejo- 
Following the approach in [https://github.com/nextcloud/text/pull/7981](https://github.com/nextcloud/text/pull/7981), I’ve already resolved the issue with Chinese input, including problems with Chinese special characters.
After testing in my own production environment and real-world use, the bug has been fully fixed on my side.
However, I’m unable to confirm whether the fix also works for other languages.
If needed, I can provide the relevant modified source code.

---

If you want, I can also help you polish it further for GitHub tone or for a pull request description.

**Comment by ebfming** [comment]
> 2025-11-27.18-21-47.mp4 
> I can't type Chinese at all. Any progress on that?

that's the same problem

**Comment by mejo-** [comment]
Thanks so much for confirming @ebfming. I'm glad to hear that this issue is also resolved with PR #7981. The next patch releases for Nextcloud 31 + 32 will get published on December 12th. They will contain the mentioned fix.

**Comment by ebfming** [comment]
> Thanks so much for confirming [@ebfming](https://github.com/ebfming). I'm glad to hear that this issue is also resolved with PR [#7981](https://github.com/nextcloud/text/pull/7981). The next patch releases for Nextcloud 31 + 32 will get published on December 12th. They will contain the mentioned fix.

Thank you everyone. I will closely monitor the patching progress when it goes live.
